export interface Character {
  code: string;
  name: string;
}

export interface Situation {
  code: string;
  name: string;
}

export interface Work {
  id: string;
  name: string;
  baseUrl: string;
  defaultSituation: string;
  characters: Character[];
  situations: Situation[];
}

// 딕셔너리(JSON) 데이터 저장소
// 이 배열 안에 새로운 작품 객체를 추가하면 상단 드롭다운에 자동으로 반영됩니다.
export const WORKS: Work[] = [
  {
    id: "smt",
    name: "검과 마법의 도시의 빙의자",
    baseUrl: "https://mapleimage.uk/smt/",
    defaultSituation: "A1", // 초기 화면에서 보여줄 캐릭터들의 기본 상황 코드 (A1, C2 등)
    characters: [
      { code: "AA", name: "셀레나 베일" },
      { code: "BB", name: "카시아 알루온" },
      { code: "CC", name: "레오나 그랜디아" },
      { code: "DD", name: "엘리스 페르마타" },
      { code: "EE", name: "발렌티나 블랑쉬" },
      { code: "FF", name: "세르피아 우로보로스" },
      { code: "GG", name: "레비아 발리스타" },
      { code: "HH", name: "카르밀라 이그니스" },
      { code: "II", name: "실비아 윈터본" },
      { code: "JJ", name: "엘리노어 블리츠" },
      { code: "KK", name: "리산드라 미라지" },
      { code: "MM", name: "아리아드네 보이드" },
      { code: "LL", name: "에테르니아 크로노스" },
      { code: "NN", name: "모리건 그레이브" },
      { code: "OO", name: "빅토리아 솔" },
      { code: "PP", name: "발레리아 이지스" },
      { code: "QQ", name: "티타니아 오베론" },
      { code: "RR", name: "레이븐 블러드" },
      { code: "SS", name: "아리엘 그레이스" },
      { code: "TT", name: "오벨리아" },
      { code: "UU", name: "빅터" },
      { code: "VV", name: "사보이아 엘레나" },
      { code: "WW", name: "한냐" },
      { code: "XX", name: "벨" },
      { code: "YY", name: "몰리" },
      { code: "ZZ", name: "마트로냐" },
      { code: "ZA", name: "린 시라누이" },
      { code: "ZB", name: "클레어 루미스" },
      { code: "ZC", name: "자하라" },
      { code: "ZD", name: "로잘린 베넷" },
      { code: "ZE", name: "렌 포레스트" },
      { code: "ZF", name: "타샤" },
      { code: "ZG", name: "이브 더스트" },
      { code: "ZH", name: "이자벨라 바인" },
      { code: "ZI", name: "카멜리아 블랑" },
      { code: "ZJ", name: "타이라 로스" },
      { code: "ZK", name: "오로라 벨코나" },
      { code: "ZL", name: "루비아 플레임" },
      { code: "ZM", name: "세리아 폰 아크" },
      { code: "ZN", name: "릴리스 섀도우" },
      { code: "ZO", name: "크리스티나 폰 에런" },
      { code: "ZP", name: "클레오 우드" },
      { code: "ZQ", name: "페넬로페 라일락" },
      { code: "ZR", name: "로냐" },
      { code: "MA", name: "가레트 아이언사이드" },
      { code: "MB", name: "드라젠 볼코프" },
      { code: "MC", name: "테일리" },
      { code: "MD", name: "알라릭 손" },
      { code: "ME", name: "베인 실라스" },
      { code: "MF", name: "케일런 스톤하트" },
      { code: "MG", name: "핀 오코넬" },
      { code: "MH", name: "카이토" },
      { code: "MI", name: "루시안 폰 테르미나" },
      { code: "MJ", name: "아드리안 폰 크로스" },
      { code: "USR1", name: "플레이어,검사" },
      { code: "USR2", name: "플레이어,마법사" },
      { code: "USR3", name: "플레이어,로그" },
    ],
    situations: [
      { code: "A1", name: "평상시, 약간 기쁨" },
      { code: "A2", name: "야릇한" },
      { code: "A3", name: "장난스러운" },
      { code: "A4", name: "귀엽게 화냄" },
      { code: "A5", name: "분노" },
      { code: "A6", name: "경멸" },
      { code: "A7", name: "삐짐" },
      { code: "A8", name: "슬픔/울음" },
      { code: "A9", name: "살짝 부끄러움" },
      { code: "A10", name: "부끄러워하며 당황" },
      { code: "A11", name: "예상치 못함, 깜짝놀람" },
      { code: "A12", name: "난처함" },
      { code: "A13", name: "감동" },
      { code: "A14", name: "자신감" },
      { code: "A15", name: "절망" },
      { code: "A16", name: "겁먹음" },
      { code: "A17", name: "짜증" },
      { code: "A18", name: "결연함" },
      { code: "A19", name: "걱정" },
      { code: "A20", name: "신기, 호기심" },
      { code: "A21", name: "비웃음" },
      { code: "A22", name: "취함" },
      { code: "A23", name: "한숨" },
      { code: "B1", name: "허그" },
      { code: "B2", name: "행복하게 품에 안김" },
      { code: "B3", name: "품에 안겨 움" },
      { code: "B4", name: "키스" },
      { code: "B5", name: "C가 U에게 팔짱을 낌" },
      { code: "B6", name: "U가 C를 공주님안기함" },
      { code: "B7", name: "U가 흥분해서 C를 넘어뜨림" },
      { code: "B8", name: "C가 흥분해서 U를 넘어뜨림" },
      { code: "B9", name: "C가 U에게 손잡고 끌려감" },
      { code: "B10", name: "U가 C에게 손잡고 끌려감" },
      { code: "B11", name: "잠" },
      { code: "B12", name: "심한 부상" },
      { code: "B13", name: "속옷차림" },
      { code: "B14", name: "속옷차림 보여 부끄러움" },
      { code: "B15", name: "판치라" },
      { code: "B16", name: "목욕중" },
      { code: "B17", name: "목욕 보여 부끄러움" },
      { code: "B18", name: "옷 벗는 중" },
      { code: "B19", name: "속옷 벗는 중" },
      { code: "B20", name: "결혼식" },
      { code: "B21", name: "쓰다듬받음" },
      { code: "B22", name: "볼꼬집힘" },
      { code: "C1", name: "기본" },
      { code: "C2", name: "전투" },
      { code: "C3", name: "중독" },
      { code: "C4", name: "기절" },
      { code: "C5", name: "부상" },
      { code: "C6", name: "최음" },
      { code: "C7", name: "사령" },
      { code: "T1", name: "실전훈련" },
      { code: "T2", name: "명상" },
      { code: "N1", name: "정상위 삽입" },
      { code: "N2", name: "정상위 삽입 절정" },
      { code: "N3", name: "후배위 삽입" },
      { code: "N4", name: "후배위 삽입 절정" },
      { code: "N5", name: "기승위 삽입" },
      { code: "N6", name: "기승위 절정" },
      { code: "N7", name: "입위 삽입" },
      { code: "N8", name: "입위 삽입 절정" },
      { code: "N9", name: "파이즈리 시작" },
      { code: "N10", name: "파이즈리 사정" },
      { code: "N11", name: "파이즈리 후" },
      { code: "N12", name: "펠라치오 시작" },
      { code: "N13", name: "펠라치오 사정" },
      { code: "N14", name: "펠라치오 후" },
      { code: "N15", name: "가슴 만짐" },
      { code: "N16", name: "젖꼭지 핥음" },
      { code: "N17", name: "보지 만짐" },
      { code: "N18", name: "보지 핥음" },
      { code: "N19", name: "딥키스" },
      { code: "N20", name: "자위" },
      { code: "N24", name: "교배 프레스" },
      { code: "N25", name: "들박" },
      { code: "N26", name: "69" },
      { code: "N27", name: "벽 끼임 앞면" },
      { code: "N29", name: "벽 끼임 펠라" },
      { code: "N30", name: "파일드라이버 섹스" },
      { code: "N31", name: "3P" },
      { code: "N32", name: "갱뱅" },
      { code: "N33", name: "대딸" },
      { code: "N34", name: "수유 대딸" },
      { code: "N35", name: "뒷스마타" },
      { code: "N36", name: "스팽킹" },
      { code: "N37", name: "배 복종 자세" },
      { code: "N38", name: "보지 벌려 보여줌" },
      { code: "N39", name: "임신 누드" },
      { code: "N40", name: "임신 중 삽입" },
      { code: "N41", name: "임신 중 삽입 절정" },
      { code: "N42", name: "애널 섹스" },
      { code: "N43", name: "풋잡" },
      { code: "N44", name: "겨드랑이 애무" },
      { code: "N45", name: "배빵" },
      { code: "N46", name: "상대를 씻겨줌" },
      { code: "N47", name: "몸을 맡기고 씻겨짐" },
      { code: "N48", name: "에로 마사지 앞" },
      { code: "N49", name: "에로 마사지 뒤" },
      { code: "N50", name: "완전 함락" },
      { code: "N51", name: "필로 토크" },
      { code: "N52", name: "공중 구속" },
      { code: "N53", name: "삼각 목마" },
      { code: "N54", name: "의자 구속" },
      { code: "N55", name: "구속 핑거링" },
      { code: "N56", name: "구속 바이브 흥분" },
      { code: "N57", name: "NTR 가슴 움켜쥠" },
      { code: "N58", name: "NTR 풀넬슨" },
      { code: "N59", name: "NTR 야외 로터" },
      { code: "N60", name: "NTR 야외 로터 참는 중" },
      { code: "N61", name: "NTR 야외 로터 절정" },
      { code: "N62", name: "NTR 카메라 앞" },
      { code: "N63", name: "NTR 강제 키스" },
      { code: "N64", name: "보지 애무 절정" },
      { code: "N65", name: "커닐링구스 절정" },
      { code: "N66", name: "측위 삽입" },
      { code: "N67", name: "측위 삽입 절정" },
      { code: "N68", name: "프론본 삽입" },
      { code: "N69", name: "프론본 삽입 절정" },
      { code: "DE1", name: "슬라임 패배시" },
      { code: "DE2", name: "촉수 함정, 미믹, 라플라시아 패배시" },
      { code: "DE3", name: "고블린, 코볼트, 오크, 아크데몬 패배시" },
      { code: "DE5", name: "서큐버스 패배시" },
      { code: "101", name: "전투1" },
      { code: "102", name: "전투2" },
      { code: "103", name: "전투3" },
      
    ]
  },
  {
    id: "nnu",
    name: "능력자 배틀물인데 능력이 없음",
    baseUrl: "https://mapleimage.uk/nnu/",
    defaultSituation: "A0", // 초기 화면에서 보여줄 캐릭터들의 기본 상황 코드 (A1, C2 등)
    characters: [
      { code: "AA", name: "김민아" },
      { code: "BB", name: "정수민" },
      { code: "CC", name: "오다현" },
      { code: "DD", name: "이벨린" },
      { code: "EE", name: "한소윤" },
      { code: "FF", name: "미오" },
      { code: "GG", name: "최유나" },
      { code: "HH", name: "강연우" },
      { code: "II", name: "윤시우" },
      { code: "JJ", name: "류징위" },
      { code: "KK", name: "이사벨라" },
      { code: "MM", name: "천신이" },
      { code: "LL", name: "카트로나" },
      { code: "NN", name: "소피아" },
      { code: "OO", name: "천신이" },
      { code: "PP", name: "루팡" },
      { code: "QQ", name: "임채아" },
      { code: "RR", name: "가브리엘라" },
      { code: "SS", name: "카에데" },
      { code: "TT", name: "이네스" },
      { code: "UU", name: "오민주" },
      { code: "VV", name: "이서윤" },
      { code: "WW", name: "한예서" },
      { code: "XX", name: "엠마" },
      { code: "YY", name: "아멜리아" },
      { code: "ZZ", name: "한예린" },
      { code: "ZA", name: "아오이" },
      { code: "ZB", name: "오드리" },
      { code: "MA", name: "김씨" },
      { code: "MB", name: "리암" },
      { code: "MC", name: "박준호" },
      { code: "MD", name: "소스케" },
      { code: "ME", name: "신홍만" },
      { code: "USR", name: "플레이어,여캐플" },

    ],
    situations: [
      { code: "A0", name: "프로필, 첫등장" },
      { code: "A1", name: "평상시, 약간 기쁨" },
      { code: "A2", name: "야릇한" },
      { code: "A3", name: "장난스러운" },
      { code: "A4", name: "귀엽게 화냄" },
      { code: "A5", name: "분노" },
      { code: "A6", name: "경멸" },
      { code: "A7", name: "삐짐" },
      { code: "A8", name: "슬픔/울음" },
      { code: "A9", name: "살짝 부끄러움" },
      { code: "A10", name: "부끄러워하며 당황" },
      { code: "A11", name: "예상치 못함, 깜짝놀람" },
      { code: "A12", name: "난처함" },
      { code: "A13", name: "감동" },
      { code: "A14", name: "자신감" },
      { code: "A15", name: "절망" },
      { code: "A16", name: "겁먹음" },
      { code: "A17", name: "짜증" },
      { code: "A18", name: "결연함" },
      { code: "A19", name: "걱정" },
      { code: "A20", name: "신기, 호기심" },
      { code: "A21", name: "비웃음" },
      { code: "A22", name: "취함" },
      { code: "A23", name: "한숨" },
      { code: "B1", name: "허그" },
      { code: "B2", name: "행복하게 품에 안김" },
      { code: "B3", name: "품에 안겨 움" },
      { code: "B4", name: "키스" },
      { code: "B5", name: "C가 U에게 팔짱을 낌" },
      { code: "B6", name: "U가 C를 공주님안기함" },
      { code: "B7", name: "U가 흥분해서 C를 넘어뜨림" },
      { code: "B8", name: "C가 흥분해서 U를 넘어뜨림" },
      { code: "B9", name: "C가 U에게 손잡고 끌려감" },
      { code: "B10", name: "U가 C에게 손잡고 끌려감" },
      { code: "B11", name: "잠" },
      { code: "B12", name: "심한 부상" },
      { code: "B13", name: "속옷차림" },
      { code: "B14", name: "속옷차림 보여 부끄러움" },
      { code: "B15", name: "판치라" },
      { code: "B16", name: "목욕중" },
      { code: "B17", name: "목욕 보여 부끄러움" },
      { code: "B18", name: "옷 벗는 중" },
      { code: "B19", name: "속옷 벗는 중" },
      { code: "B20", name: "결혼식" },
      { code: "B21", name: "쓰다듬받음" },
      { code: "B22", name: "볼꼬집힘" },
      { code: "C1", name: "기본" },
      { code: "C2", name: "전투" },
      { code: "C3", name: "중독" },
      { code: "C4", name: "기절" },
      { code: "C5", name: "부상" },
      { code: "C6", name: "최음" },
      { code: "C7", name: "사령" },
      { code: "T1", name: "실전훈련" },
      { code: "T2", name: "명상" },
      { code: "N1", name: "정상위 삽입" },
      { code: "N2", name: "정상위 삽입 절정" },
      { code: "N3", name: "후배위 삽입" },
      { code: "N4", name: "후배위 삽입 절정" },
      { code: "N5", name: "기승위 삽입" },
      { code: "N6", name: "기승위 절정" },
      { code: "N7", name: "입위 삽입" },
      { code: "N8", name: "입위 삽입 절정" },
      { code: "N9", name: "파이즈리 시작" },
      { code: "N10", name: "파이즈리 사정" },
      { code: "N11", name: "파이즈리 후" },
      { code: "N12", name: "펠라치오 시작" },
      { code: "N13", name: "펠라치오 사정" },
      { code: "N14", name: "펠라치오 후" },
      { code: "N15", name: "가슴 만짐" },
      { code: "N16", name: "젖꼭지 핥음" },
      { code: "N17", name: "보지 만짐" },
      { code: "N18", name: "보지 핥음" },
      { code: "N19", name: "딥키스" },
      { code: "N20", name: "자위" },
      { code: "N24", name: "교배 프레스" },
      { code: "N25", name: "들박" },
      { code: "N26", name: "69" },
      { code: "N27", name: "벽 끼임 앞면" },
      { code: "N29", name: "벽 끼임 펠라" },
      { code: "N30", name: "파일드라이버 섹스" },
      { code: "N31", name: "3P" },
      { code: "N32", name: "갱뱅" },
      { code: "N33", name: "대딸" },
      { code: "N34", name: "수유 대딸" },
      { code: "N35", name: "뒷스마타" },
      { code: "N36", name: "스팽킹" },
      { code: "N37", name: "배 복종 자세" },
      { code: "N38", name: "보지 벌려 보여줌" },
      { code: "N39", name: "임신 누드" },
      { code: "N40", name: "임신 중 삽입" },
      { code: "N41", name: "임신 중 삽입 절정" },
      { code: "N42", name: "애널 섹스" },
      { code: "N43", name: "풋잡" },
      { code: "N44", name: "겨드랑이 애무" },
      { code: "N45", name: "배빵" },
      { code: "N46", name: "상대를 씻겨줌" },
      { code: "N47", name: "몸을 맡기고 씻겨짐" },
      { code: "N48", name: "에로 마사지 앞" },
      { code: "N49", name: "에로 마사지 뒤" },
      { code: "N50", name: "완전 함락" },
      { code: "N51", name: "필로 토크" },
      { code: "N52", name: "공중 구속" },
      { code: "N53", name: "삼각 목마" },
      { code: "N54", name: "의자 구속" },
      { code: "N55", name: "구속 핑거링" },
      { code: "N56", name: "구속 바이브 흥분" },
      { code: "N57", name: "NTR 가슴 움켜쥠" },
      { code: "N58", name: "NTR 풀넬슨" },
      { code: "N59", name: "NTR 야외 로터" },
      { code: "N60", name: "NTR 야외 로터 참는 중" },
      { code: "N61", name: "NTR 야외 로터 절정" },
      { code: "N62", name: "NTR 카메라 앞" },
      { code: "N63", name: "NTR 강제 키스" },
      { code: "N64", name: "보지 애무 절정" },
      { code: "N65", name: "커닐링구스 절정" },
      { code: "N66", name: "측위 삽입" },
      { code: "N67", name: "측위 삽입 절정" },
      { code: "N68", name: "프론본 삽입" },
      { code: "N69", name: "프론본 삽입 절정" },
      { code: "N70", name: "착의 섹스" },
      { code: "N71", name: "착의 섹스 절정" },
      { code: "N72", name: "착의 펠라" },
      { code: "N73", name: "착의 펠라 사정" },
      { code: "N74", name: "착의 펠라 후" },
      { code: "101", name: "능력 사용" },
      
    ]
  },
  
  // 아래에 쉼표(,)를 찍고 새로운 작품을 계속 추가할 수 있습니다.
  {
    id: "example-second-work",
    name: "강호일통(준비중)",
    baseUrl: "",
    defaultSituation: "A1",
    characters: [

    ],
    situations: [

    ]
  },
];
